name: Update Repositories

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to update
        required: true
        type: choice
        options:
          - dev
          - main

      ScheduleJobs:
        description: ScheduleJobs
        type: boolean

      tracking-api:
        description: tracking-api
        type: boolean

      PassApi:
        description: PassApi
        type: boolean

      seguimiento-api:
        description: seguimiento-api
        type: boolean


jobs:

  build-matrix:
    name: Build Repositories Matrix
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Build Matrix
        id: set-matrix
        run: |
          repos=()
          if [ "${{ inputs.ScheduleJobs }}" = "true" ]; then
          repos+=("ScheduleJobs")
          fi
          if [ "${{ inputs.tracking-api }}" = "true" ]; then
          repos+=("tracking-api")
          fi
          if [ "${{ inputs.PassApi }}" = "true" ]; then
          repos+=("PassApi")
          fi
          if [ "${{ inputs.seguimiento-api }}" = "true" ]; then
          repos+=("seguimiento-api")
          fi
          
          matrix_json=$(printf '%s\n' "${repos[@]}" | jq -R . | jq -s -c .)
          echo "Selected repositories: $matrix_json"

          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT


  update-repositories:
    name: Sync Repositories
    needs: build-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    steps:
      - name: Trigger Repository CI
        id: dispatch
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ADMIN-BO-TECH
          repo: ${{ matrix.repo }}
          github_token: ${{ secrets.BOTECH_TOKEN }}
          workflow_file_name: continous-integration.yml
          ref: ${{ inputs.environment }}
          client_payload: '{"branch": "${{ inputs.environment }}"}'
          wait_interval: 30

      - name: Trigger Update And Deploy
        id: dispatch
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ADMIN-BO-TECH
          repo: ${{ matrix.repo }}
          github_token: ${{ secrets.BOTECH_TOKEN }}
          workflow_file_name: update-library-version-and-publish.yml
          ref: ${{ inputs.environment }}
          client_payload: '{"branch": "${{ inputs.environment }}"}'
          wait_interval: 30


      - name: Add repository result to summary
        if: always()
        run: |
          REPOSITORY="${{ matrix.repo }}"
          RESULT="${{ steps.dispatch.outputs.result }}"
          if [ "$RESULT" = "SUCCESS" ]; then
            STATUS="✅ SUCCESS TO INVOKE"
          else
            STATUS="❌ FAILED TO INVOKE"
          fi
          echo "$REPOSITORY -> $STATUS" >> summary.txt
      - name: Summary Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: result-${{ matrix.repo }}
          path: summary.txt


  summary:
    name: Final Summary
    needs: update-repositories
    runs-on: ubuntu-latest
    if: always()

    steps:
      - uses: actions/download-artifact@v4
      - name: Build Final Report
        run: |
          
          echo "## Library Update Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          for file in result-*/*.txt; do
            cat "$file" >> $GITHUB_STEP_SUMMARY
          done