name: Update Repositories

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to update
        required: true
        type: choice
        options:
          - dev
          - main

      ScheduleJobs:
        description: ScheduleJobs
        type: boolean

      tracking-api:
        description: tracking-api
        type: boolean

      PassApi:
        description: PassApi
        type: boolean

      seguimiento-api:
        description: seguimiento-api
        type: boolean


jobs:

  build-matrix:
    name: Build Repositories Matrix
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Build Matrix
        id: set-matrix
        run: |
          repos=()
          if [ "${{ inputs.ScheduleJobs }}" = "true" ]; then
          repos+=("ScheduleJobs")
          fi
          if [ "${{ inputs.tracking-api }}" = "true" ]; then
          repos+=("tracking-api")
          fi
          if [ "${{ inputs.PassApi }}" = "true" ]; then
          repos+=("PassApi")
          fi
          if [ "${{ inputs.seguimiento-api }}" = "true" ]; then
          repos+=("seguimiento-api")
          fi
          
          matrix_json=$(printf '%s\n' "${repos[@]}" | jq -R . | jq -s -c .)
          echo "Selected repositories: $matrix_json"

          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT


  update-repositories:
    name: Sync Repositories
    needs: build-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    steps:
      - name: Wait for Workflow Action
        uses: kamilchodola/wait-for-workflow-action@1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.BOTECH_TOKEN }}
          workflow_id: 'continous-integration.yml'
          max_wait_minutes: '10'
          interval: '5'
          timeout: '60'
          org_name: 'ADMIN-BO-TECH'
          repo_name: "${{ matrix.repo }}"
          ref: '${{ ENVIRONMENT }}'
